// Pre-seeded authentic Gulbarga, Karnataka stores & Indian grocery catalog

export interface Store {
  id: string;
  legacy_id: string;
  name_en: string;
  name_hi: string;
  description_en: string;
  description_hi: string;
  type: 'restaurant' | 'grocery';
  category: string;
  address: string;
  latitude: number;
  longitude: number;
  phone: string;
  logo_url: string;
  cover_image_url: string;
  avg_rating: number;
  total_ratings: number;
  delivery_radius_km: number;
  avg_prep_time_minutes: number;
  min_order_value: number;
  is_active: boolean;
  is_accepting_orders: boolean;
  source: 'external' | 'manual';
  last_synced_at: string;
}

export interface Product {
  id: string;
  legacy_id: string;
  store_id: string;
  category_id: string;
  category_name_en: string;
  category_name_hi: string;
  name_en: string;
  name_hi: string;
  description_en: string;
  description_hi: string;
  price: number;
  discounted_price: number;
  image_url: string;
  is_veg: boolean;
  unit: 'kg' | 'g' | 'litre' | 'ml' | 'piece' | 'pack';
  stock_quantity: number;
  variants: { id: string; name_en: string; name_hi: string; price_delta: number }[];
  is_available: boolean;
  gst_rate: number;
  last_synced_at: string;
}

export const INITIAL_STORES: Store[] = [
  {
    id: 's01',
    legacy_id: 'EXT_REST_001',
    name_en: 'Hotel Heritage Gulbarga',
    name_hi: 'होटल हेरिटेज गुलबर्गा',
    description_en: 'Legendary Gulbarga Mutton Tahari, Chicken Dum Biryani & Kebabs',
    description_hi: 'प्रसिद्ध गुलबर्गा मटन तहरी, चिकन दम बिरयानी और कबाब',
    type: 'restaurant',
    category: 'Gulbarga Specials',
    address: 'Sedam Road, Near Central Bus Stand, Gulbarga',
    latitude: 17.3340,
    longitude: 76.8402,
    phone: '+91 8472 251010',
    logo_url: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=300&q=80',
    cover_image_url: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=1000&q=80',
    avg_rating: 4.7,
    total_ratings: 1840,
    delivery_radius_km: 8.5,
    avg_prep_time_minutes: 25,
    min_order_value: 149,
    is_active: true,
    is_accepting_orders: true,
    source: 'external',
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 's02',
    legacy_id: 'EXT_REST_002',
    name_en: 'Annapurna Jolada Rotti Meals',
    name_hi: 'अन्नपूर्णा जोलद रोट्टी भोजन',
    description_en: 'Authentic North Karnataka Jowar Rotti, Stuffed Brinjal (Yennegai) & Shenga Chutney',
    description_hi: 'पारंपरिक उत्तर कर्नाटक ज्वार की रोटी, येन्नेगाई और शेंगा चटनी',
    type: 'restaurant',
    category: 'North Karnataka Pure Veg',
    address: 'Super Market, Khuba Plot, Gulbarga',
    latitude: 17.3280,
    longitude: 76.8285,
    phone: '+91 8472 234050',
    logo_url: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?w=300&q=80',
    cover_image_url: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=1000&q=80',
    avg_rating: 4.8,
    total_ratings: 2450,
    delivery_radius_km: 7.0,
    avg_prep_time_minutes: 20,
    min_order_value: 99,
    is_active: true,
    is_accepting_orders: true,
    source: 'external',
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 's03',
    legacy_id: 'EXT_REST_003',
    name_en: 'New Taj Darbar & Biryani',
    name_hi: 'न्यू ताज दरबार और बिरयानी',
    description_en: 'Mutton Tahari, Sheermal, Chicken Fry & Gulbarga Dum Chai',
    description_hi: 'मटन तहरी, शीरमाल, चिकन फ्राई और दम चाय',
    type: 'restaurant',
    category: 'Biryani & Kebabs',
    address: 'Station Road, Near Railway Station, Gulbarga',
    latitude: 17.3395,
    longitude: 76.8480,
    phone: '+91 8472 267890',
    logo_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=300&q=80',
    cover_image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=1000&q=80',
    avg_rating: 4.5,
    total_ratings: 980,
    delivery_radius_km: 8.0,
    avg_prep_time_minutes: 30,
    min_order_value: 199,
    is_active: true,
    is_accepting_orders: true,
    source: 'external',
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 's04',
    legacy_id: 'EXT_GROC_001',
    name_en: 'Gulbarga Super Kirana & Dal Mart',
    name_hi: 'गुलबर्गा सुपर किराना और दाल मार्ट',
    description_en: 'Direct APMC Mandi GI-Tagged Gulbarga Toor Dal, Premium Atta, Ghee & Spices',
    description_hi: 'मंडी से सीधे जीआई-टैग गुलबर्गा तूर दाल, प्रीमियम आटा, शुद्ध घी और मसाले',
    type: 'grocery',
    category: 'Atta, Rice & Dal',
    address: 'APMC Market Yard, Sedam Road, Gulbarga',
    latitude: 17.3310,
    longitude: 76.8450,
    phone: '+91 8472 288120',
    logo_url: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=300&q=80',
    cover_image_url: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=1000&q=80',
    avg_rating: 4.9,
    total_ratings: 3120,
    delivery_radius_km: 10.0,
    avg_prep_time_minutes: 15,
    min_order_value: 149,
    is_active: true,
    is_accepting_orders: true,
    source: 'external',
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 's05',
    legacy_id: 'EXT_GROC_002',
    name_en: 'Nandini Dairy & Fresh Veggies',
    name_hi: 'नंदिनी डेयरी और ताजी सब्जियां',
    description_en: 'Daily fresh KMF Nandini Milk, Curd, Paneer & Morning Harvest Farm Greens',
    description_hi: 'ताजा नंदिनी दूध, दही, पनीर और खेत से ताजी सब्जियां',
    type: 'grocery',
    category: 'Dairy, Milk & Bread',
    address: 'MSK Mill Road, Bhavani Nagar, Gulbarga',
    latitude: 17.3240,
    longitude: 76.8210,
    phone: '+91 8472 299440',
    logo_url: 'https://images.unsplash.com/photo-1528732263440-4dd1a18a4cc2?w=300&q=80',
    cover_image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=1000&q=80',
    avg_rating: 4.8,
    total_ratings: 1450,
    delivery_radius_km: 6.5,
    avg_prep_time_minutes: 10,
    min_order_value: 49,
    is_active: true,
    is_accepting_orders: true,
    source: 'external',
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 's07',
    legacy_id: 'EXT_REST_004',
    name_en: "Hotel Lumbini's Grand",
    name_hi: 'होटल लुम्बिनीज ग्रैंड',
    description_en: 'Fine dining North Karnataka Royal Thali, Cashew Gravies, Tandoori & Mutton Sukka',
    description_hi: 'शाही उत्तर कर्नाटक थाली, काजू ग्रेवी, तंदूरी और प्रसिद्ध मटन सुक्का',
    type: 'restaurant',
    category: 'Gulbarga Specials',
    address: 'Sedam Road, Opp. High Court Bench, Gulbarga',
    latitude: 17.3365,
    longitude: 76.8420,
    phone: '+91 8472 277112',
    logo_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=300&q=80',
    cover_image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1000&q=80',
    avg_rating: 4.8,
    total_ratings: 1920,
    delivery_radius_km: 9.0,
    avg_prep_time_minutes: 25,
    min_order_value: 199,
    is_active: true,
    is_accepting_orders: true,
    source: 'external',
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 's08',
    legacy_id: 'EXT_REST_005',
    name_en: 'New Bombay Restaurant & Tahari House',
    name_hi: 'न्यू बॉम्बे रेस्टोरेंट और तहरी हाउस',
    description_en: 'Gulbarga historic Mutton Dum Tahari, Dalcha Khana, Bheja Fry & Sheermal',
    description_hi: 'ऐतिहासिक गुलबर्गा मटन दम तहरी, दालचा खाना, भेजा फ्राई और शीरमाल',
    type: 'restaurant',
    category: 'Biryani & Kebabs',
    address: 'Muslim Chowk, Super Market Main Road, Gulbarga',
    latitude: 17.3295,
    longitude: 76.8310,
    phone: '+91 8472 244550',
    logo_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=300&q=80',
    cover_image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=1000&q=80',
    avg_rating: 4.9,
    total_ratings: 3410,
    delivery_radius_km: 8.0,
    avg_prep_time_minutes: 20,
    min_order_value: 149,
    is_active: true,
    is_accepting_orders: true,
    source: 'external',
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 's09',
    legacy_id: 'EXT_REST_006',
    name_en: 'Hotel Pariwar Pure Veg',
    name_hi: 'होटल परिवार शुद्ध शाकाहारी',
    description_en: 'Crisp Gulbarga Benne Dosa, Shenga Holige with Pure Ghee & Filter Coffee',
    description_hi: 'कुरकुरा बेन्ने डोसा, देसी घी से बनी शेंगा होलिगे और दक्षिण भारतीय फिल्टर कॉफी',
    type: 'restaurant',
    category: 'North Karnataka Pure Veg',
    address: 'MSK Mill Road, Station Bazaar, Gulbarga',
    latitude: 17.3260,
    longitude: 76.8240,
    phone: '+91 8472 221980',
    logo_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=300&q=80',
    cover_image_url: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=1000&q=80',
    avg_rating: 4.7,
    total_ratings: 1520,
    delivery_radius_km: 7.5,
    avg_prep_time_minutes: 15,
    min_order_value: 99,
    is_active: true,
    is_accepting_orders: true,
    source: 'external',
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 's10',
    legacy_id: 'EXT_REST_007',
    name_en: 'Sri Guru Sharanabasaveshwara Khanavali',
    name_hi: 'श्री गुरु शरणबसवेश्वर खानावली',
    description_en: 'Heritage North Karnataka Kadak Jolada Rotti, Badane Ennegai & Shenga Chutney Pudi',
    description_hi: 'पारंपरिक कड़क जोलद रोट्टी, बदने येन्नेगाई, शेंगा चटनी पुड़ी और ताजा दही',
    type: 'restaurant',
    category: 'North Karnataka Pure Veg',
    address: 'Temple Ring Road, Near Sharanabasaveshwara Appa Temple, Gulbarga',
    latitude: 17.3270,
    longitude: 76.8390,
    phone: '+91 8472 255440',
    logo_url: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=300&q=80',
    cover_image_url: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=1000&q=80',
    avg_rating: 4.9,
    total_ratings: 4200,
    delivery_radius_km: 8.0,
    avg_prep_time_minutes: 15,
    min_order_value: 99,
    is_active: true,
    is_accepting_orders: true,
    source: 'external',
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 's11',
    legacy_id: 'EXT_REST_008',
    name_en: 'Hotel Grand Mehfil & Tandoor',
    name_hi: 'होटल ग्रैंड महफ़िल और तंदूर',
    description_en: 'Charcoal Smoked Tandoori Murgh, Malai Tikka, Mutton Rogan Josh & Dal Makhani',
    description_hi: 'कोयले पर भुना तंदूरी मुर्ग, मलाई टिक्का, मटन रोगन जोश और दाल मखनी',
    type: 'restaurant',
    category: 'Biryani & Kebabs',
    address: 'Station Road, Opp. Head Post Office, Gulbarga',
    latitude: 17.3380,
    longitude: 76.8460,
    phone: '+91 8472 233771',
    logo_url: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=300&q=80',
    cover_image_url: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=1000&q=80',
    avg_rating: 4.6,
    total_ratings: 1150,
    delivery_radius_km: 8.5,
    avg_prep_time_minutes: 30,
    min_order_value: 199,
    is_active: true,
    is_accepting_orders: true,
    source: 'external',
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 's12',
    legacy_id: 'EXT_REST_009',
    name_en: 'New Athidhi Family Restaurant',
    name_hi: 'न्यू अतिथि फैमिली रेस्टोरेंट',
    description_en: 'Shahi Kaju Curry, Gulbarga Famous Malpuri Sweet, Veg Biryani & Crispy Corn',
    description_hi: 'शाही काजू करी, गुलबर्गा की सुप्रसिद्ध मालपुरी मिठाई, वेज बिरयानी और क्रिस्पी कॉर्न',
    type: 'restaurant',
    category: 'Gulbarga Specials',
    address: 'Humnabad Ring Road, Near Kusnoor, Gulbarga',
    latitude: 17.3420,
    longitude: 76.8350,
    phone: '+91 8472 266200',
    logo_url: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=300&q=80',
    cover_image_url: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=1000&q=80',
    avg_rating: 4.7,
    total_ratings: 1680,
    delivery_radius_km: 9.0,
    avg_prep_time_minutes: 20,
    min_order_value: 149,
    is_active: true,
    is_accepting_orders: true,
    source: 'external',
    last_synced_at: new Date().toISOString(),
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  // Products for Hotel Heritage (Restaurant)
  {
    id: 'p01',
    legacy_id: 'EXT_PROD_101',
    store_id: 's01',
    category_id: 'c01',
    category_name_en: 'Gulbarga Specials',
    category_name_hi: 'गुलबर्गा स्पेशल',
    name_en: 'Authentic Gulbarga Mutton Tahari',
    name_hi: 'प्रमाणिक गुलबर्गा मटन तहरी',
    description_en: 'Gulbarga signature spiced long-grain rice slow-cooked with tender succulent mutton pieces',
    description_hi: 'कोमल मटन और सुगंधित मसालों से पकी गुलबर्गा की सुप्रसिद्ध पारंपरिक तहरी',
    price: 320,
    discounted_price: 280,
    image_url: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=600&q=80',
    is_veg: false,
    unit: 'pack',
    stock_quantity: 45,
    variants: [
      { id: 'v1', name_en: 'Regular (Serves 1)', name_hi: 'साधारण (1 व्यक्ति)', price_delta: 0 },
      { id: 'v2', name_en: 'Special Jumbo (Serves 2)', name_hi: 'जंबो (2 व्यक्ति)', price_delta: 140 }
    ],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 'p02',
    legacy_id: 'EXT_PROD_102',
    store_id: 's01',
    category_id: 'c01',
    category_name_en: 'Gulbarga Specials',
    category_name_hi: 'गुलबर्गा स्पेशल',
    name_en: 'Chicken Dum Biryani (Gulbarga Style)',
    name_hi: 'चिकन दम बिरयानी (गुलबर्गा स्टाइल)',
    description_en: 'Richly spiced marinated chicken cooked on sealed dum with saffron aroma',
    description_hi: 'केसर की महक और देसी मसालों के साथ पकाई गई लज़ीज़ चिकन दम बिरयानी',
    price: 240,
    discounted_price: 220,
    image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&q=80',
    is_veg: false,
    unit: 'pack',
    stock_quantity: 60,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 'p03',
    legacy_id: 'EXT_PROD_103',
    store_id: 's01',
    category_id: 'c01',
    category_name_en: 'Gulbarga Specials',
    category_name_hi: 'गुलबर्गा स्पेशल',
    name_en: 'Gulbarga Mirchi Bhajji & Masala',
    name_hi: 'गुलबर्गा मिर्ची भज्जी और मसाला',
    description_en: 'Crispy fried Bhavnagri green chillies stuffed with tangy peanut and tamarind spice',
    description_hi: 'कुरकुरी तली हुई मसालेदार मिर्ची भज्जी, मूंगफली और इमली चटनी के साथ',
    price: 80,
    discounted_price: 70,
    image_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&q=80',
    is_veg: true,
    unit: 'piece',
    stock_quantity: 80,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },

  // Products for Annapurna (Restaurant - Veg)
  {
    id: 'p04',
    legacy_id: 'EXT_PROD_104',
    store_id: 's02',
    category_id: 'c02',
    category_name_en: 'North Karnataka Veg',
    category_name_hi: 'उत्तर कर्नाटक शुद्ध शाकाहारी',
    name_en: 'Special Jolada Rotti Full Meal',
    name_hi: 'स्पेशल जोलद रोट्टी संपूर्ण थाली',
    description_en: '3 hot Jowar rottis, Stuffed Yennegai (Brinjal), Shenga (Peanut) Chutney, Junka & Curd',
    description_hi: '3 गरमा-गरम ज्वार की रोटियां, येन्नेगाई बैंगन, शेंगा चटनी, झुनका और ताजा दही',
    price: 160,
    discounted_price: 149,
    image_url: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&q=80',
    is_veg: true,
    unit: 'pack',
    stock_quantity: 50,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 'p05',
    legacy_id: 'EXT_PROD_105',
    store_id: 's02',
    category_id: 'c02',
    category_name_en: 'North Karnataka Veg',
    category_name_hi: 'उत्तर कर्नाटक शुद्ध शाकाहारी',
    name_en: 'Yennegai Ennegai (Brinjal Curry)',
    name_hi: 'येन्नेगाई (भरवां बैंगन करी)',
    description_en: 'Traditional roasted sesame and peanut gravy stuffed small tender brinjals',
    description_hi: 'तिल और मूंगफली की सुगंधित ग्रेवी में बने पारंपरिक भरवां बैंगन',
    price: 110,
    discounted_price: 99,
    image_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&q=80',
    is_veg: true,
    unit: 'pack',
    stock_quantity: 40,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 'p06',
    legacy_id: 'EXT_PROD_106',
    store_id: 's02',
    category_id: 'c02',
    category_name_en: 'North Karnataka Veg',
    category_name_hi: 'उत्तर कर्नाटक शुद्ध शाकाहारी',
    name_en: 'Gulbarga Special Badam Milk',
    name_hi: 'गुलबर्गा स्पेशल बादाम दूध',
    description_en: 'Chilled rich saffron badam milk with pistachio slivers',
    description_hi: 'केसर, पिस्ता और असली बादाम से बना ठंडा स्वादिष्ट दूध',
    price: 65,
    discounted_price: 55,
    image_url: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&q=80',
    is_veg: true,
    unit: 'piece',
    stock_quantity: 75,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },

  // Products for Gulbarga Super Kirana (Grocery)
  {
    id: 'p07',
    legacy_id: 'EXT_PROD_201',
    store_id: 's04',
    category_id: 'c03',
    category_name_en: 'Atta, Rice & Dal',
    category_name_hi: 'आटा, चावल और दाल',
    name_en: 'Gulbarga GI-Tagged Premium Toor Dal (1kg)',
    name_hi: 'गुलबर्गा जीआई-टैग प्रीमियम तूर दाल (1 किग्रा)',
    description_en: 'Nationally famous Geographical Indication (GI) certified Gulbarga Pigeon Pea/Toor Dal, fast cooking and high protein',
    description_hi: 'भौगोलिक संकेतक (GI) प्रमाणित विश्वप्रसिद्ध गुलबर्गा तूर दाल, उच्च प्रोटीन और लाजवाब स्वाद',
    price: 195,
    discounted_price: 175,
    image_url: 'https://images.unsplash.com/photo-1585994192701-59dd04299924?w=600&q=80',
    is_veg: true,
    unit: 'kg',
    stock_quantity: 120,
    variants: [
      { id: 'v1', name_en: '1 kg Pack', name_hi: '1 किग्रा पैक', price_delta: 0 },
      { id: 'v2', name_en: '5 kg Value Saver', name_hi: '5 किग्रा बचत पैक', price_delta: 680 }
    ],
    is_available: true,
    gst_rate: 0.0, // Untreated pulses 0%
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 'p08',
    legacy_id: 'EXT_PROD_202',
    store_id: 's04',
    category_id: 'c03',
    category_name_en: 'Atta, Rice & Dal',
    category_name_hi: 'आटा, चावल और दाल',
    name_en: 'Aashirvaad Sharbati Whole Wheat Atta (5kg)',
    name_hi: 'आशीर्वाद शरबती शुद्ध गेहूं आटा (5 किग्रा)',
    description_en: '100% pure Madhya Pradesh Sharbati grains for extra soft rotis',
    description_hi: '100% शरबती गेहूं के दानों से बना नरम और फूली रोटियों के लिए आटा',
    price: 295,
    discounted_price: 265,
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80',
    is_veg: true,
    unit: 'pack',
    stock_quantity: 65,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 'p09',
    legacy_id: 'EXT_PROD_203',
    store_id: 's04',
    category_id: 'c04',
    category_name_en: 'Edible Oils & Ghee',
    category_name_hi: 'खाने का तेल और शुद्ध घी',
    name_en: 'Fortune Sunlite Refined Sunflower Oil (1L Pouch)',
    name_hi: 'फॉर्च्यून सनलाइट रिफाइंड सूरजमुखी तेल (1 लीटर)',
    description_en: 'Enriched with Vitamin A & D, light and healthy cooking oil',
    description_hi: 'विटामिन ए और डी से भरपूर, हल्का और स्वास्थ्यवर्धक कुकिंग तेल',
    price: 155,
    discounted_price: 139,
    image_url: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80',
    is_veg: true,
    unit: 'litre',
    stock_quantity: 80,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 'p10',
    legacy_id: 'EXT_PROD_204',
    store_id: 's04',
    category_id: 'c05',
    category_name_en: 'Spices & Masalas',
    category_name_hi: 'मसाले और तड़का',
    name_en: 'Everest Super Garam Masala (100g)',
    name_hi: 'एवरेस्ट सुपर गरम मसाला (100 ग्राम)',
    description_en: 'A blend of 13 aromatic spices for authentic North Karnataka curry aroma',
    description_hi: '13 सुगंधित खड़े मसालों का समृद्ध मिश्रण करी के स्वाद को बढ़ाने हेतु',
    price: 90,
    discounted_price: 82,
    image_url: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80',
    is_veg: true,
    unit: 'pack',
    stock_quantity: 110,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },

  // Products for Nandini & Fresh Greens (Grocery)
  {
    id: 'p11',
    legacy_id: 'EXT_PROD_205',
    store_id: 's05',
    category_id: 'c06',
    category_name_en: 'Dairy, Milk & Bread',
    category_name_hi: 'डेयरी, दूध और ब्रेड',
    name_en: 'Nandini Toned Fresh Milk (500ml)',
    name_hi: 'नंदिनी टोन्ड ताजा दूध (500 मिली)',
    description_en: 'Karnataka Milk Federation (KMF) pasteurized fresh toned milk',
    description_hi: 'केएमएफ कर्नाटक दुग्ध महासंघ का ताजा पाश्चुरीकृत टोन्ड दूध',
    price: 24,
    discounted_price: 24,
    image_url: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&q=80',
    is_veg: true,
    unit: 'ml',
    stock_quantity: 95,
    variants: [],
    is_available: true,
    gst_rate: 0.0,
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 'p12',
    legacy_id: 'EXT_PROD_206',
    store_id: 's05',
    category_id: 'c07',
    category_name_en: 'Fresh Farm Vegetables',
    category_name_hi: 'ताजी सब्जियां',
    name_en: 'Fresh Gulbarga Red Onions (1kg)',
    name_hi: 'ताजे गुलबर्गा लाल प्याज (1 किग्रा)',
    description_en: 'Hand-picked pungent and firm local farm fresh onions',
    description_hi: 'स्थानीय खेतों से चुने गए ताजे, कड़क और पौष्टिक लाल प्याज',
    price: 45,
    discounted_price: 38,
    image_url: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=600&q=80',
    is_veg: true,
    unit: 'kg',
    stock_quantity: 150,
    variants: [],
    is_available: true,
    gst_rate: 0.0,
    last_synced_at: new Date().toISOString(),
  },

  // Products for Hotel Lumbini's Grand (s07)
  {
    id: 'p13',
    legacy_id: 'EXT_PROD_301',
    store_id: 's07',
    category_id: 'c01',
    category_name_en: 'Gulbarga Specials',
    category_name_hi: 'गुलबर्गा स्पेशल',
    name_en: 'Lumbini Royal North Karnataka Thali',
    name_hi: 'लुम्बिनी रॉयल उत्तर कर्नाटक थाली',
    description_en: '3 hot Jolada Rottis, Badane Yennegai, Kaalu Palya, Dal, Shenga Chutney, Curd & Holige',
    description_hi: '3 गरमा-गरम जोलद रोट्टी, बदने येन्नेगाई, कालू पाल्या, दाल, शेंगा चटनी, दही और मीठी होलिगे',
    price: 240,
    discounted_price: 220,
    image_url: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&q=80',
    is_veg: true,
    unit: 'pack',
    stock_quantity: 60,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 'p14',
    legacy_id: 'EXT_PROD_302',
    store_id: 's07',
    category_id: 'c02',
    category_name_en: 'Main Course & Curries',
    category_name_hi: 'मुख्य व्यंजन और करी',
    name_en: 'Paneer Butter Masala (Lumbini Special)',
    name_hi: 'पनीर बटर मसाला (लुम्बिनी स्पेशल)',
    description_en: 'Soft cottage cheese cubes in rich cashew-tomato velvet butter gravy',
    description_hi: 'काजू-टमाटर की मखमली बटर ग्रेवी में पके नरम पनीर के टुकड़े',
    price: 210,
    discounted_price: 195,
    image_url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&q=80',
    is_veg: true,
    unit: 'pack',
    stock_quantity: 40,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 'p15',
    legacy_id: 'EXT_PROD_303',
    store_id: 's07',
    category_id: 'c01',
    category_name_en: 'Gulbarga Specials',
    category_name_hi: 'गुलबर्गा स्पेशल',
    name_en: 'Gulbarga Mutton Sukka Roast',
    name_hi: 'गुलबर्गा मटन सुक्का रोस्ट',
    description_en: 'Slow-roasted dry mutton tossed in freshly ground Kalaburagi spices, curry leaves and pepper',
    description_hi: 'कलबुर्गी के ताजे खड़े मसालों और करी पत्तों में भूना हुआ मसालेदार मटन सुक्का',
    price: 340,
    discounted_price: 310,
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80',
    is_veg: false,
    unit: 'pack',
    stock_quantity: 35,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },

  // Products for New Bombay Restaurant & Tahari House (s08)
  {
    id: 'p16',
    legacy_id: 'EXT_PROD_401',
    store_id: 's08',
    category_id: 'c03',
    category_name_en: 'Biryani & Kebabs',
    category_name_hi: 'बिरयानी और कबाब',
    name_en: 'Bombay Special Mutton Dum Tahari',
    name_hi: 'बॉम्बे स्पेशल मटन दम तहरी',
    description_en: 'Century-old recipe of fragrant short-grain rice cooked with fresh tender mutton and curd in copper deg',
    description_hi: 'तांबे की देग में कोमल मटन, दही और पारंपरिक मसालों से पकी विश्वप्रसिद्ध दम तहरी',
    price: 310,
    discounted_price: 275,
    image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&q=80',
    is_veg: false,
    unit: 'pack',
    stock_quantity: 70,
    variants: [
      { id: 'v10', name_en: 'Single Plate (Serves 1)', name_hi: 'एक प्लेट (1 व्यक्ति)', price_delta: 0 },
      { id: 'v11', name_en: 'Double Plate (Serves 2)', name_hi: 'डबल प्लेट (2 व्यक्ति)', price_delta: 240 }
    ],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 'p17',
    legacy_id: 'EXT_PROD_402',
    store_id: 's08',
    category_id: 'c01',
    category_name_en: 'Gulbarga Specials',
    category_name_hi: 'गुलबर्गा स्पेशल',
    name_en: 'Gulbarga Dalcha Khana with Bagara Rice',
    name_hi: 'गुलबर्गा दालचा खाना बगार राइस के साथ',
    description_en: 'Slow-simmered bottle gourd and chana dal gravy paired with hot ghee-tempered Bagara rice',
    description_hi: 'कद्दू और चना दाल से बना स्वादिष्ट दालचा और गरमा-गरम घी-तड़का बघारा चावल',
    price: 180,
    discounted_price: 160,
    image_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&q=80',
    is_veg: true,
    unit: 'pack',
    stock_quantity: 50,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 'p18',
    legacy_id: 'EXT_PROD_403',
    store_id: 's08',
    category_id: 'c03',
    category_name_en: 'Biryani & Kebabs',
    category_name_hi: 'बिरयानी और कबाब',
    name_en: 'Gulbarga Mutton Bheja Fry Masala',
    name_hi: 'गुलबर्गा मटन भेजा फ्राई मसाला',
    description_en: 'Delicate mutton brain roasted in spicy onion, green chili and pepper masala',
    description_hi: 'प्याज, हरी मिर्च और काली मिर्च के तीखे मसाले में भूना मटन भेजा फ्राई',
    price: 260,
    discounted_price: 240,
    image_url: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&q=80',
    is_veg: false,
    unit: 'pack',
    stock_quantity: 30,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },

  // Products for Hotel Pariwar Pure Veg (s09)
  {
    id: 'p19',
    legacy_id: 'EXT_PROD_501',
    store_id: 's09',
    category_id: 'c02',
    category_name_en: 'North Karnataka Pure Veg',
    category_name_hi: 'उत्तर कर्नाटक शाकाहारी',
    name_en: 'Gulbarga Special Benne Dosa',
    name_hi: 'गुलबर्गा स्पेशल बेन्ने डोसा',
    description_en: 'Crisp golden fermented dosa roasted with generous dollops of fresh white butter, served with potato palya',
    description_hi: 'ताजे सफेद मक्खन से सिका कुरकुरा डोसा, आलू पाल्या और नारियल-लाल चटनी के साथ',
    price: 95,
    discounted_price: 85,
    image_url: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&q=80',
    is_veg: true,
    unit: 'pack',
    stock_quantity: 80,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 'p20',
    legacy_id: 'EXT_PROD_502',
    store_id: 's09',
    category_id: 'c01',
    category_name_en: 'Gulbarga Specials',
    category_name_hi: 'गुलबर्गा स्पेशल',
    name_en: 'Traditional Shenga Holige with Pure Ghee (2 pcs)',
    name_hi: 'पारंपरिक शेंगा होलिगे शुद्ध घी के साथ (2 नग)',
    description_en: 'Heritage North Karnataka sweet flatbread stuffed with roasted groundnut and jaggery paste, drizzled with A2 ghee',
    description_hi: 'भुनी मूंगफली और गुड़ से बनी प्रसिद्ध उत्तर कर्नाटक मीठी होलिगे, शुद्ध घी के साथ',
    price: 85,
    discounted_price: 75,
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&q=80',
    is_veg: true,
    unit: 'pack',
    stock_quantity: 65,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 'p21',
    legacy_id: 'EXT_PROD_503',
    store_id: 's09',
    category_id: 'c02',
    category_name_en: 'North Karnataka Pure Veg',
    category_name_hi: 'उत्तर कर्नाटक शाकाहारी',
    name_en: 'Mysore Masala Dosa with Chutneys',
    name_hi: 'मैसूर मसाला डोसा चटनी के साथ',
    description_en: 'Classic crispy red garlic-chutney smeared dosa stuffed with seasoned potato masala',
    description_hi: 'लाल लहसुन चटनी और स्वादिष्ट आलू मसाले से भरा कुरकुरा मैसूर डोसा',
    price: 90,
    discounted_price: 80,
    image_url: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&q=80',
    is_veg: true,
    unit: 'pack',
    stock_quantity: 90,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },

  // Products for Sri Guru Sharanabasaveshwara Khanavali (s10)
  {
    id: 'p22',
    legacy_id: 'EXT_PROD_601',
    store_id: 's10',
    category_id: 'c02',
    category_name_en: 'North Karnataka Pure Veg',
    category_name_hi: 'उत्तर कर्नाटक शाकाहारी',
    name_en: 'Traditional Kadak Jolada Rotti Oota',
    name_hi: 'पारंपरिक कड़क जोलद रोट्टी भोजन',
    description_en: '3 crisp hand-patted Jowar flatbreads, Badane Ennegai, sprouted pulses, Shenga Pudi, Jhunka, Mosaru',
    description_hi: '3 कड़क हाथ से बनी ज्वार की रोटियां, भरवां बैंगन, मूंग पाल्या, शेंगा पुड़ी, झुनका और दही',
    price: 160,
    discounted_price: 140,
    image_url: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&q=80',
    is_veg: true,
    unit: 'pack',
    stock_quantity: 100,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 'p23',
    legacy_id: 'EXT_PROD_602',
    store_id: 's10',
    category_id: 'c01',
    category_name_en: 'Gulbarga Specials',
    category_name_hi: 'गुलबर्गा स्पेशल',
    name_en: 'Shenga Chutney Pudi & Buffalo Curd Plate',
    name_hi: 'शेंगा चटनी पुड़ी और गाढ़ा भैंस का दही',
    description_en: 'Spicy ground peanut powder roasted with garlic and red chilies, served with thick fresh local curd',
    description_hi: 'लहसुन और लाल मिर्च से बनी तीखी मूंगफली चटनी पुड़ी व ताजा गाढ़ा दही',
    price: 60,
    discounted_price: 55,
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&q=80',
    is_veg: true,
    unit: 'pack',
    stock_quantity: 80,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 'p24',
    legacy_id: 'EXT_PROD_603',
    store_id: 's10',
    category_id: 'c02',
    category_name_en: 'North Karnataka Pure Veg',
    category_name_hi: 'उत्तर कर्नाटक शाकाहारी',
    name_en: 'Badane Ennegai (Stuffed Brinjal Curry)',
    name_hi: 'बदने येन्नेगाई (भरवां बैंगन करी)',
    description_en: 'Baby brinjals slow cooked in a rich, nutty gravy of roasted peanuts, sesame, tamarind and jaggery',
    description_hi: 'तिल, मूंगफली, इमली और गुड़ की गाढ़ी स्वादिष्ट ग्रेवी में पके छोटे भरवां बैंगन',
    price: 110,
    discounted_price: 95,
    image_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&q=80',
    is_veg: true,
    unit: 'pack',
    stock_quantity: 50,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },

  // Products for Hotel Grand Mehfil & Tandoor (s11)
  {
    id: 'p25',
    legacy_id: 'EXT_PROD_701',
    store_id: 's11',
    category_id: 'c03',
    category_name_en: 'Biryani & Kebabs',
    category_name_hi: 'बिरयानी और कबाब',
    name_en: 'Charcoal Smoked Tandoori Murgh (Full)',
    name_hi: 'तंदूरी मुर्ग कोयला भुना (पूरा)',
    description_en: 'Whole spring chicken marinated overnight in Kashmiri degi mirch, hung curd and mustard oil',
    description_hi: 'कश्मीरी देगी मिर्च और सरसों के तेल में मैरीनेट कर तंदूर में भुना पूरा चिकन',
    price: 420,
    discounted_price: 380,
    image_url: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&q=80',
    is_veg: false,
    unit: 'pack',
    stock_quantity: 40,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 'p26',
    legacy_id: 'EXT_PROD_702',
    store_id: 's11',
    category_id: 'c03',
    category_name_en: 'Biryani & Kebabs',
    category_name_hi: 'बिरयानी और कबाब',
    name_en: 'Murgh Malai Tikka (6 pcs)',
    name_hi: 'मुर्ग मलाई टिक्का (6 पीस)',
    description_en: 'Boneless chicken cubes marinated in heavy cream, cardamom, cheese and cashew paste grilled over embers',
    description_hi: 'क्रीम, इलायची, पनीर और काजू के लेप में लिपटे मुंह में घुलने वाले मलाईदार कबाब',
    price: 290,
    discounted_price: 260,
    image_url: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&q=80',
    is_veg: false,
    unit: 'pack',
    stock_quantity: 50,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },

  // Products for New Athidhi Family Restaurant (s12)
  {
    id: 'p27',
    legacy_id: 'EXT_PROD_801',
    store_id: 's12',
    category_id: 'c01',
    category_name_en: 'Gulbarga Specials',
    category_name_hi: 'गुलबर्गा स्पेशल',
    name_en: 'Shahi Kaju Curry (Whole Cashew Masala)',
    name_hi: 'शाही काजू करी (साबुत काजू मसाला)',
    description_en: 'Generous portion of crisp golden fried whole cashews in royal spiced onion-tomato makhani gravy',
    description_hi: 'सुनहरे काजू के दानों से सजी शाही प्याज-टमाटर मखनी ग्रेवी वाली लजीज करी',
    price: 230,
    discounted_price: 210,
    image_url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&q=80',
    is_veg: true,
    unit: 'pack',
    stock_quantity: 60,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 'p28',
    legacy_id: 'EXT_PROD_802',
    store_id: 's12',
    category_id: 'c01',
    category_name_en: 'Gulbarga Specials',
    category_name_hi: 'गुलबर्गा स्पेशल',
    name_en: 'Gulbarga Famous Malpuri Sweet (2 pcs)',
    name_hi: 'गुलबर्गा प्रसिद्ध मालपुरी मिठाई (2 नग)',
    description_en: 'Iconic Gulbarga festive sweet made from thickened milk and flour, fried to golden amber and dipped in saffron syrup',
    description_hi: 'मावा और केसर की चाशनी में डूबी गुलबर्गा की अत्यंत लोकप्रिय पारंपरिक मालपुरी',
    price: 90,
    discounted_price: 80,
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&q=80',
    is_veg: true,
    unit: 'pack',
    stock_quantity: 75,
    variants: [],
    is_available: true,
    gst_rate: 5.0,
    last_synced_at: new Date().toISOString(),
  }
];
